#!/bin/bash
# Script completo para traducir el widget Table a español (incluyendo TODOS los textos de ayuda)
# Complete script to translate the Table widget to Spanish (including ALL help texts)

WIDGET_DIR="/usr/share/zabbix/modules/tableMain"

echo "🌍 Iniciando traducción completa del widget a español..."
echo "🌍 Starting complete translation of widget to Spanish..."

# Crear respaldos
echo "📦 Creando respaldos..."
echo "📦 Creating backups..."
find "$WIDGET_DIR" -name "*.php" -exec cp {} {}.backup \;

# ============================================
# TRADUCCIONES PRINCIPALES - WidgetForm.php
# ============================================
echo "📝 Traduciendo WidgetForm.php..."
echo "📝 Translating WidgetForm.php..."
FILE="$WIDGET_DIR/includes/WidgetForm.php"

sed -i "s/_('Host groups')/_('Grupos de hosts')/g" "$FILE"
sed -i "s/_('Hosts')/_('Hosts')/g" "$FILE"
sed -i "s/_('Item filter')/_('Filtro de items')/g" "$FILE"
sed -i "s/_('Item filter type')/_('Tipo de filtro de items')/g" "$FILE"
sed -i "s/_('Itemids')/_('IDs de items')/g" "$FILE"
sed -i "s/_('Tags')/_('Etiquetas')/g" "$FILE"
sed -i "s/_('Item filter update only')/_('Actualizar solo filtro de items')/g" "$FILE"
sed -i "s/_('Host tags')/_('Etiquetas de host')/g" "$FILE"
sed -i "s/_('And\/Or')/_('Y\/O')/g" "$FILE"
sed -i "s/_('Or')/_('O')/g" "$FILE"
sed -i "s/_('Show problems')/_('Mostrar problemas')/g" "$FILE"
sed -i "s/_('All')/_('Todos')/g" "$FILE"
sed -i "s/_('Unsuppressed')/_('No suprimidos')/g" "$FILE"
sed -i "s/_('None')/_('Ninguno')/g" "$FILE"
sed -i "s/_('Layout')/_('Diseño')/g" "$FILE"
sed -i "s/_('Horizontal')/_('Horizontal')/g" "$FILE"
sed -i "s/_('Vertical')/_('Vertical')/g" "$FILE"
sed -i "s/_('3 Column')/_('3 Columnas')/g" "$FILE"
sed -i "s/_('Column per pattern')/_('Columna por patrón')/g" "$FILE"
sed -i "s/_('Item grouping')/_('Agrupación de items')/g" "$FILE"
sed -i "s/_('Grouping delimiter')/_('Delimitador de agrupación')/g" "$FILE"
sed -i "s/_('Show column header')/_('Mostrar encabezado de columna')/g" "$FILE"
sed -i "s/_('Off')/_('Desactivado')/g" "$FILE"
sed -i "s/_('Items')/_('Items')/g" "$FILE"
sed -i "s/_('Bar gauge layout')/_('Diseño de barra')/g" "$FILE"
sed -i "s/_('Column')/_('Columna')/g" "$FILE"
sed -i "s/_('Row')/_('Fila')/g" "$FILE"
sed -i "s/_('Bar gauge tooltip')/_('Tooltip de barra')/g" "$FILE"
sed -i "s/_('Max')/_('Máximo')/g" "$FILE"
sed -i "s/_('Sum')/_('Suma')/g" "$FILE"
sed -i "s/_('Disallow host broadcasting')/_('Deshabilitar difusión de host')/g" "$FILE"
sed -i "s/_('Aggregate all hosts')/_('Agregar todos los hosts')/g" "$FILE"
sed -i "s/_('Show item grouping only')/_('Mostrar solo agrupación de items')/g" "$FILE"
sed -i "s/_('Autoselect first cell')/_('Seleccionar automáticamente primera celda')/g" "$FILE"
sed -i "s/_('Show footer row')/_('Mostrar fila de pie')/g" "$FILE"
sed -i "s/_('No footer')/_('Sin pie')/g" "$FILE"
sed -i "s/_('Average')/_('Promedio')/g" "$FILE"
sed -i "s/_('Item header name')/_('Nombre de encabezado de item')/g" "$FILE"
sed -i "s/_('Host header name')/_('Nombre de encabezado de host')/g" "$FILE"
sed -i "s/_('Add reset row')/_('Agregar fila de reinicio')/g" "$FILE"
sed -i "s/_('Metric label')/_('Etiqueta de métrica')/g" "$FILE"
sed -i "s/_('Order by')/_('Ordenar por')/g" "$FILE"
sed -i "s/_('Host name')/_('Nombre de host')/g" "$FILE"
sed -i "s/_('Item value')/_('Valor de item')/g" "$FILE"
sed -i "s/_('Item')/_('Item')/g" "$FILE"
sed -i "s/_('Order')/_('Orden')/g" "$FILE"
sed -i "s/_('Top N')/_('Top N')/g" "$FILE"
sed -i "s/_('Bottom N')/_('Bottom N')/g" "$FILE"
sed -i "s/_('Limit')/_('Límite')/g" "$FILE"
sed -i "s/_('Item name')/_('Nombre de item')/g" "$FILE"
sed -i "s/_('Host')/_('Host')/g" "$FILE"

# ============================================
# TRADUCCIONES - widget.edit.php (TEXTOS DE AYUDA)
# ============================================
echo "📝 Traduciendo widget.edit.php (textos de ayuda)..."
echo "📝 Translating widget.edit.php (help texts)..."
FILE="$WIDGET_DIR/views/widget.edit.php"

# Textos de ayuda de widget.edit.php
sed -i "s/_('Choose whether you want to filter using itemids or tags from the filtering widget widget')/_('Elige si quieres filtrar usando IDs de items o etiquetas del widget de filtrado')/g" "$FILE"
sed -i "s/_('Currently, only the Item navigator widget broadcasts tags, but only if the Item navigator is configured with a \\\\\'Group by\\\\' of \\\\\'Item tag value\\\\\'')/_('Actualmente, solo el widget Navegador de items transmite etiquetas, pero solo si el Navegador de items está configurado con Agrupar por valor de etiqueta de item')/g" "$FILE"
sed -i "s/_('Checking this box means that this widget will only display metrics when there is an Item filter set')/_('Marcar esta casilla significa que este widget solo mostrará métricas cuando haya un filtro de items configurado')/g" "$FILE"
sed -i "s/_('If the Item filter is a widget, a selection from that referred widget is the only way this widget will display metrics')/_('Si el filtro de items es un widget, una selección de ese widget referido es la única forma en que este widget mostrará métricas')/g" "$FILE"
sed -i "s/_('Horizontal - Host in first column. Values per item\/metrics in subsequent columns')/_('Horizontal - Host en la primera columna. Valores por item\/métricas en columnas subsiguientes')/g" "$FILE"
sed -i "s/_('Vertical - Item\/Metric name in first column. Values per host in subsequent columns')/_('Vertical - Nombre de item\/métrica en la primera columna. Valores por host en columnas subsiguientes')/g" "$FILE"
sed -i "s/_('3 Column - Item\/Metric name in first column. Host in second column. Values per item\/metrics in third column')/_('3 Columnas - Nombre de item\/métrica en la primera columna. Host en la segunda columna. Valores por item\/métricas en la tercera columna')/g" "$FILE"
sed -i "s/_('Column Per pattern - Each item pattern specified receives its own column')/_('Columna por patrón - Cada patrón de item especificado recibe su propia columna')/g" "$FILE"
sed -i "s/_('The tags chosen will be displayed in first column of the table.')/_('Las etiquetas elegidas se mostrarán en la primera columna de la tabla.')/g" "$FILE"
sed -i "s/_('Alternatively, you can just group the metrics by host, which will omit the first column, ')/_('Alternativamente, puedes agrupar las métricas por host, lo que omitirá la primera columna, ')/g" "$FILE"
sed -i "s/_('by specifying a grouping of \\\\\'\\{HOST.HOST\\}\\\\\'')/_('especificando una agrupación de {HOST.HOST}')/g" "$FILE"
sed -i "s/_('Allows for customizing the Item grouping delimiter.')/_('Permite personalizar el delimitador de agrupación de items.')/g" "$FILE"
sed -i "s/_('By default, the delimiter is \\\\' \/ \\\\' of nothing is specified here.')/_('Por defecto, el delimitador es \\' \/ \\' si no se especifica nada aquí.')/g" "$FILE"
sed -i "s/_('Choose how to display the bar gauges in the table. Selecting \\\\\'Column\\\\\' will show proportions within each column, while selecting \\\\\'Row\\\\\' will show proportions within each row.')/_('Elige cómo mostrar las barras en la tabla. Seleccionar Columna mostrará proporciones dentro de cada columna, mientras que seleccionar Fila mostrará proporciones dentro de cada fila.')/g" "$FILE"
sed -i "s/_('When hovering over a bar gauge in the table it will show what the corresponding value cell\\\\\'s proportion is as a percentage.')/_('Al pasar el mouse sobre una barra en la tabla mostrará qué proporción tiene la celda de valor correspondiente como porcentaje.')/g" "$FILE"
sed -i "s/_('The default is to show the ratio to the max value. However, by choosing \\\\\'Sum\\\\\' you can show what the corresponding value cell\\\\\'s proportion is to the sum of all value cells, or you can show no tooltip.')/_('El valor predeterminado es mostrar la proporción al valor máximo. Sin embargo, al elegir Suma puedes mostrar qué proporción tiene la celda de valor correspondiente respecto a la suma de todas las celdas de valor, o puedes no mostrar tooltip.')/g" "$FILE"
sed -i "s/_('NOTE: The proportion shown will use the choice from \\\\\'Bar gauge layout\\\\\' above')/_('NOTA: La proporción mostrada usará la elección de Diseño de barra de arriba')/g" "$FILE"
sed -i "s/_('Turns off the ability to broadcast the hostid to other widgets when hosts are visible in the table')/_('Desactiva la capacidad de transmitir el ID de host a otros widgets cuando los hosts son visibles en la tabla')/g" "$FILE"
sed -i "s/_('Checking this box will aggregate all values, by the item grouping above, across all hosts')/_('Marcar esta casilla agregará todos los valores, por la agrupación de items de arriba, en todos los hosts')/g" "$FILE"
sed -i "s/_('NOTE: Checking this box requires a \\\\\'Column patterns aggregation\\\\\' to be set in the \\\\\'Items\\\\\' ')/_('NOTA: Marcar esta casilla requiere que se establezca una Agregación de patrones de columna en Items ')/g" "$FILE"
sed -i "s/_('configuration popup under the \\\\\'Advanced Configuration\\\\\' section')/_('en el popup de configuración bajo la sección Configuración avanzada')/g" "$FILE"
sed -i "s/_('OTHER NOTE: when using this \\\\\'Host ordering\\\\\' options from the Advanced configuration section below are ignored')/_('OTRA NOTA: al usar esto, las opciones de Ordenamiento de host de la sección Configuración avanzada a continuación se ignoran')/g" "$FILE"
sed -i "s/_('Checking this box will cause only the \\\\\'Item grouping\\\\\' column to be displayed')/_('Marcar esta casilla hará que solo se muestre la columna Agrupación de items')/g" "$FILE"
sed -i "s/_('This is useful for when you want to use this widget to act as a filter to other widgets instead of showing metrics.')/_('Esto es útil cuando quieres usar este widget para actuar como filtro de otros widgets en lugar de mostrar métricas.')/g" "$FILE"
sed -i "s/_('NOTE: Checking this box automatically causes \\\\\'Broadcast from grouped column\\\\\' to be checked for each Item pattern specified')/_('NOTA: Marcar esta casilla automáticamente hace que se marque Difundir desde columna agrupada para cada patrón de item especificado')/g" "$FILE"
sed -i "s/_('Checking this box will cause the first value and host cell to be automatically selected')/_('Marcar esta casilla hará que la primera celda de valor y host se seleccione automáticamente')/g" "$FILE"
sed -i "s/_('If set, a footer row will be added at the bottom of the table')/_('Si se establece, se agregará una fila de pie en la parte inferior de la tabla')/g" "$FILE"
sed -i "s/_('Changes the header name from the default of \\\\\'Items\\\\\' to this value when using all layouts except Horizontal')/_('Cambia el nombre del encabezado del valor predeterminado Items a este valor cuando se usan todos los diseños excepto Horizontal')/g" "$FILE"
sed -i "s/_('Changes the header name from the default of \\\\\'Host\\\\\' to this value when using all layouts except Vertical')/_('Cambia el nombre del encabezado del valor predeterminado Host a este valor cuando se usan todos los diseños excepto Vertical')/g" "$FILE"
sed -i "s/_('By typing a value into this box you will add a reset row to the widget with the value you entered.')/_('Al escribir un valor en esta casilla agregarás una fila de reinicio al widget con el valor que ingresaste.')/g" "$FILE"
sed -i "s/_('A reset row is used with layouts of \\\\\'Horizontal\\\\\', \\\\\'3 Column\\\\\', and \\\\\'Column per pattern\\\\\'.')/_('Una fila de reinicio se usa con los diseños Horizontal, 3 Columnas y Columna por patrón.')/g" "$FILE"
sed -i "s/_('After a click on the reset row value, connected widgets will reset back to their base configurations.')/_('Después de hacer clic en el valor de la fila de reinicio, los widgets conectados se reiniciarán a sus configuraciones base.')/g" "$FILE"
sed -i "s/_('Set the row (Vertical) or column (Horizontal\/3 Column) label for the metric name')/_('Establece la etiqueta de fila (Vertical) o columna (Horizontal\/3 Columnas) para el nombre de la métrica')/g" "$FILE"
sed -i "s/_('Supported macros:')/_('Macros soportados:')/g" "$FILE"
sed -i "s/_('Limit applies to each \"Item pattern\" separately')/_('El límite se aplica a cada patrón de item por separado')/g" "$FILE"

# ============================================
# TRADUCCIONES - column.edit.php
# ============================================
echo "📝 Traduciendo column.edit.php..."
echo "📝 Translating column.edit.php..."
FILE="$WIDGET_DIR/views/column.edit.php"

# Etiquetas principales
sed -i "s/_('Column title')/_('Título de columna')/g" "$FILE"
sed -i "s/_('Broadcast from grouped column')/_('Difundir desde columna agrupada')/g" "$FILE"
sed -i "s/_('Item tags')/_('Etiquetas de item')/g" "$FILE"
sed -i "s/_('Base color')/_('Color base')/g" "$FILE"
sed -i "s/_('Font color')/_('Color de fuente')/g" "$FILE"
sed -i "s/_('Display value as')/_('Mostrar valor como')/g" "$FILE"
sed -i "s/_('Numeric')/_('Numérico')/g" "$FILE"
sed -i "s/_('Text')/_('Texto')/g" "$FILE"
sed -i "s/_('URL')/_('URL')/g" "$FILE"
sed -i "s/_('Display')/_('Visualización')/g" "$FILE"
sed -i "s/_('As is')/_('Como está')/g" "$FILE"
sed -i "s/_('Bar')/_('Barra')/g" "$FILE"
sed -i "s/_('Indicators')/_('Indicadores')/g" "$FILE"
sed -i "s/_('Min')/_('Mínimo')/g" "$FILE"
sed -i "s/_('Thresholds')/_('Umbrales')/g" "$FILE"
sed -i "s/_('Threshold')/_('Umbral')/g" "$FILE"
sed -i "s/_('Decimal places')/_('Decimales')/g" "$FILE"
sed -i "s/_('Highlights')/_('Resaltados')/g" "$FILE"
sed -i "s/_('Regular expression')/_('Expresión regular')/g" "$FILE"
sed -i "s/_('URL display mode')/_('Modo de visualización URL')/g" "$FILE"
sed -i "s/_('Custom')/_('Personalizado')/g" "$FILE"
sed -i "s/_('URL display override')/_('Sobrescribir visualización URL')/g" "$FILE"
sed -i "s/_('URL customization')/_('Personalización de URL')/g" "$FILE"
sed -i "s/_('Open URL in new tab')/_('Abrir URL en nueva pestaña')/g" "$FILE"
sed -i "s/_('Advanced configuration')/_('Configuración avanzada')/g" "$FILE"
sed -i "s/_('Column patterns aggregation')/_('Agregación de patrones de columna')/g" "$FILE"
sed -i "s/_('Aggregation function')/_('Función de agregación')/g" "$FILE"
sed -i "s/_('History data')/_('Datos históricos')/g" "$FILE"
sed -i "s/_('Auto')/_('Auto')/g" "$FILE"
sed -i "s/_('History')/_('Histórico')/g" "$FILE"
sed -i "s/_('Trends')/_('Tendencias')/g" "$FILE"
sed -i "s/_('Override footer')/_('Sobrescribir pie')/g" "$FILE"
sed -i "s/_('No override')/_('Sin sobrescribir')/g" "$FILE"
sed -i "s/_('Include itemids in cell')/_('Incluir IDs de items en celda')/g" "$FILE"
sed -i "s/_('Update column')/_('Actualizar columna')/g" "$FILE"
sed -i "s/_('New column')/_('Nueva columna')/g" "$FILE"
sed -i "s/_('Update')/_('Actualizar')/g" "$FILE"
sed -i "s/_('Add')/_('Agregar')/g" "$FILE"
sed -i "s/_('Remove')/_('Eliminar')/g" "$FILE"
sed -i "s/_('User macros')/_('Macros de usuario')/g" "$FILE"

# TEXTOS DE AYUDA de column.edit.php
sed -i "s/_('Only used when \\\\\'Layout\\\\\' is set to \\\\\'Column per pattern\\\\\'')/_('Solo se usa cuando el Diseño está configurado como Columna por patrón')/g" "$FILE"
sed -i "s/_('Checking this box means that the itemid will be broadcasted to listening widgets by clicking the cell in the column with the grouping value')/_('Marcar esta casilla significa que el ID del item se transmitirá a los widgets que escuchan al hacer clic en la celda de la columna con el valor de agrupación')/g" "$FILE"
sed -i "s/_('This is useful for when you have multiple columns and you want to broadcast multiple metrics to be plotted simultaneously')/_('Esto es útil cuando tienes múltiples columnas y quieres transmitir múltiples métricas para graficarlas simultáneamente')/g" "$FILE"
sed -i "s/_('If you know the item key pattern, you can specify it instead of the item name pattern by typing: \"key=<ITEM_KEY>\" for each pattern you want.')/_('Si conoces el patrón de clave de item, puedes especificarlo en lugar del patrón de nombre escribiendo: \"key=<CLAVE_ITEM>\" para cada patrón que desees.')/g" "$FILE"
sed -i "s/_('Wildcards are still supported for item key patterns.')/_('Los comodines aún son compatibles con los patrones de clave de item.')/g" "$FILE"
sed -i "s/_('The reason for item key pattern usage here is it is faster due to indexing.')/_('La razón para usar patrones de clave de item aquí es que es más rápido debido a la indexación.')/g" "$FILE"
sed -i "s/_('In order to find the key you need, to go the Latest data page, search for your item patterns and then check the \"Show details\" box. The key for each item will display below the item name in the \"Name\" column')/_('Para encontrar la clave que necesitas, ve a la página de Últimos datos, busca tus patrones de items y marca la casilla \"Mostrar detalles\". La clave de cada item se mostrará debajo del nombre del item en la columna \"Nombre\"')/g" "$FILE"
sed -i "s/_('Customize the display text of the URL')/_('Personaliza el texto de visualización de la URL')/g" "$FILE"
sed -i "s/_('Instead of displaying the raw URL you can set arbitrary text to display instead. The URL will be encoded into the text you enter in this text box.')/_('En lugar de mostrar la URL sin formato, puedes establecer un texto arbitrario para mostrar. La URL se codificará en el texto que ingreses en este cuadro.')/g" "$FILE"
sed -i "s/_('You can also mix macros with text. Supported macros:')/_('También puedes mezclar macros con texto. Macros soportados:')/g" "$FILE"
sed -i "s/_('Customize the entire URL')/_('Personaliza la URL completa')/g" "$FILE"
sed -i "s/_('Instead of displaying the metric value as a URL, you can leverage the hosts and items from the returned results to create a fully customized URL. You can also just simply enter any valid URL (i.e. https:\/\/www.zabbix.com)')/_('En lugar de mostrar el valor de la métrica como URL, puedes aprovechar los hosts e items de los resultados devueltos para crear una URL completamente personalizada. También puedes simplemente ingresar cualquier URL válida (ej. https:\/\/www.zabbix.com)')/g" "$FILE"
sed -i "s/_('Check this box to open the URL in a new browser tab, otherwise the link will open in the same tab')/_('Marca esta casilla para abrir la URL en una nueva pestaña del navegador, de lo contrario el enlace se abrirá en la misma pestaña')/g" "$FILE"
sed -i "s/_('Choose a function to aggregate all item patterns for this column for each host.')/_('Elige una función para agregar todos los patrones de items para esta columna por cada host.')/g" "$FILE"
sed -i "s/_('When using \\\\\'Column patterns aggregation\\\\\' include all itemids for broadcasting to other widgets')/_('Al usar Agregación de patrones de columna incluir todos los IDs de items para transmitir a otros widgets')/g" "$FILE"
sed -i "s/_('Set custom display text')/_('Establecer texto de visualización personalizado')/g" "$FILE"
sed -i "s/_('Create a fully custom URL')/_('Crear una URL completamente personalizada')/g" "$FILE"
sed -i "s/_('calculated')/_('calculado')/g" "$FILE"

echo ""
echo "✅ Traducción completada!"
echo "✅ Translation completed!"
echo ""
echo "📦 Los archivos originales están respaldados con extensión .backup"
echo "📦 Original files are backed up with .backup extension"
echo ""
echo "🔄 Ahora ejecuta:"
echo "🔄 Now run:"
echo "   sudo systemctl restart httpd"
echo ""
echo "📝 Si algo sale mal, puedes restaurar con:"
echo "📝 If something goes wrong, you can restore with:"
echo "   find $WIDGET_DIR -name '*.backup' -exec bash -c 'mv \"\$0\" \"\${0%.backup}\"' {} \;"
