#!/bin/bash
# Script completo para traducir el widget Table a español (incluyendo ayudas)
# Complete script to translate the Table widget to Spanish (including help texts)

WIDGET_DIR="/usr/share/zabbix/modules/tableMain"

echo "🌍 Iniciando traducción completa del widget a español..."
echo "🌍 Starting complete translation of widget to Spanish..."

# Crear respaldos
echo "📦 Creando respaldos..."
echo "📦 Creating backups..."
find "$WIDGET_DIR" -name "*.php" -exec cp {} {}.backup \;

# ============================================
# TRADUCCIONES PRINCIPALES - WidgetForm.php
# ============================================
echo "📝 Traduciendo WidgetForm.php..."
echo "📝 Translating WidgetForm.php..."
FILE="$WIDGET_DIR/includes/WidgetForm.php"

sed -i "s/_('Host groups')/_('Grupos de hosts')/g" "$FILE"
sed -i "s/_('Hosts')/_('Hosts')/g" "$FILE"
sed -i "s/_('Item filter')/_('Filtro de items')/g" "$FILE"
sed -i "s/_('Item filter type')/_('Tipo de filtro de items')/g" "$FILE"
sed -i "s/_('Itemids')/_('IDs de items')/g" "$FILE"
sed -i "s/_('Tags')/_('Etiquetas')/g" "$FILE"
sed -i "s/_('Item filter update only')/_('Actualizar solo filtro de items')/g" "$FILE"
sed -i "s/_('Host tags')/_('Etiquetas de host')/g" "$FILE"
sed -i "s/_('And\/Or')/_('Y\/O')/g" "$FILE"
sed -i "s/_('Or')/_('O')/g" "$FILE"
sed -i "s/_('Show problems')/_('Mostrar problemas')/g" "$FILE"
sed -i "s/_('All')/_('Todos')/g" "$FILE"
sed -i "s/_('Unsuppressed')/_('No suprimidos')/g" "$FILE"
sed -i "s/_('None')/_('Ninguno')/g" "$FILE"
sed -i "s/_('Layout')/_('Diseño')/g" "$FILE"
sed -i "s/_('Horizontal')/_('Horizontal')/g" "$FILE"
sed -i "s/_('Vertical')/_('Vertical')/g" "$FILE"
sed -i "s/_('3 Column')/_('3 Columnas')/g" "$FILE"
sed -i "s/_('Column per pattern')/_('Columna por patrón')/g" "$FILE"
sed -i "s/_('Item grouping')/_('Agrupación de items')/g" "$FILE"
sed -i "s/_('Grouping delimiter')/_('Delimitador de agrupación')/g" "$FILE"
sed -i "s/_('Show column header')/_('Mostrar encabezado de columna')/g" "$FILE"
sed -i "s/_('Off')/_('Desactivado')/g" "$FILE"
sed -i "s/_('Items')/_('Items')/g" "$FILE"
sed -i "s/_('Bar gauge layout')/_('Diseño de barra')/g" "$FILE"
sed -i "s/_('Column')/_('Columna')/g" "$FILE"
sed -i "s/_('Row')/_('Fila')/g" "$FILE"
sed -i "s/_('Bar gauge tooltip')/_('Tooltip de barra')/g" "$FILE"
sed -i "s/_('Max')/_('Máximo')/g" "$FILE"
sed -i "s/_('Sum')/_('Suma')/g" "$FILE"
sed -i "s/_('Disallow host broadcasting')/_('Deshabilitar difusión de host')/g" "$FILE"
sed -i "s/_('Aggregate all hosts')/_('Agregar todos los hosts')/g" "$FILE"
sed -i "s/_('Show item grouping only')/_('Mostrar solo agrupación de items')/g" "$FILE"
sed -i "s/_('Autoselect first cell')/_('Seleccionar automáticamente primera celda')/g" "$FILE"
sed -i "s/_('Show footer row')/_('Mostrar fila de pie')/g" "$FILE"
sed -i "s/_('No footer')/_('Sin pie')/g" "$FILE"
sed -i "s/_('Average')/_('Promedio')/g" "$FILE"
sed -i "s/_('Item header name')/_('Nombre de encabezado de item')/g" "$FILE"
sed -i "s/_('Host header name')/_('Nombre de encabezado de host')/g" "$FILE"
sed -i "s/_('Add reset row')/_('Agregar fila de reinicio')/g" "$FILE"
sed -i "s/_('Metric label')/_('Etiqueta de métrica')/g" "$FILE"
sed -i "s/_('Order by')/_('Ordenar por')/g" "$FILE"
sed -i "s/_('Host name')/_('Nombre de host')/g" "$FILE"
sed -i "s/_('Item value')/_('Valor de item')/g" "$FILE"
sed -i "s/_('Item')/_('Item')/g" "$FILE"
sed -i "s/_('Order')/_('Orden')/g" "$FILE"
sed -i "s/_('Top N')/_('Top N')/g" "$FILE"
sed -i "s/_('Bottom N')/_('Bottom N')/g" "$FILE"
sed -i "s/_('Limit')/_('Límite')/g" "$FILE"
sed -i "s/_('Item name')/_('Nombre de item')/g" "$FILE"
sed -i "s/_('Host')/_('Host')/g" "$FILE"

# ============================================
# TRADUCCIONES - column.edit.php
# ============================================
echo "📝 Traduciendo column.edit.php..."
echo "📝 Translating column.edit.php..."
FILE="$WIDGET_DIR/views/column.edit.php"

# Etiquetas principales
sed -i "s/_('Column title')/_('Título de columna')/g" "$FILE"
sed -i "s/_('Broadcast from grouped column')/_('Difundir desde columna agrupada')/g" "$FILE"
sed -i "s/_('Item tags')/_('Etiquetas de item')/g" "$FILE"
sed -i "s/_('Base color')/_('Color base')/g" "$FILE"
sed -i "s/_('Font color')/_('Color de fuente')/g" "$FILE"
sed -i "s/_('Display value as')/_('Mostrar valor como')/g" "$FILE"
sed -i "s/_('Numeric')/_('Numérico')/g" "$FILE"
sed -i "s/_('Text')/_('Texto')/g" "$FILE"
sed -i "s/_('URL')/_('URL')/g" "$FILE"
sed -i "s/_('Display')/_('Visualización')/g" "$FILE"
sed -i "s/_('As is')/_('Como está')/g" "$FILE"
sed -i "s/_('Bar')/_('Barra')/g" "$FILE"
sed -i "s/_('Indicators')/_('Indicadores')/g" "$FILE"
sed -i "s/_('Min')/_('Mínimo')/g" "$FILE"
sed -i "s/_('Thresholds')/_('Umbrales')/g" "$FILE"
sed -i "s/_('Threshold')/_('Umbral')/g" "$FILE"
sed -i "s/_('Decimal places')/_('Decimales')/g" "$FILE"
sed -i "s/_('Highlights')/_('Resaltados')/g" "$FILE"
sed -i "s/_('Regular expression')/_('Expresión regular')/g" "$FILE"
sed -i "s/_('URL display mode')/_('Modo de visualización URL')/g" "$FILE"
sed -i "s/_('Custom')/_('Personalizado')/g" "$FILE"
sed -i "s/_('URL display override')/_('Sobrescribir visualización URL')/g" "$FILE"
sed -i "s/_('URL customization')/_('Personalización de URL')/g" "$FILE"
sed -i "s/_('Open URL in new tab')/_('Abrir URL en nueva pestaña')/g" "$FILE"
sed -i "s/_('Advanced configuration')/_('Configuración avanzada')/g" "$FILE"
sed -i "s/_('Column patterns aggregation')/_('Agregación de patrones de columna')/g" "$FILE"
sed -i "s/_('Aggregation function')/_('Función de agregación')/g" "$FILE"
sed -i "s/_('History data')/_('Datos históricos')/g" "$FILE"
sed -i "s/_('Auto')/_('Auto')/g" "$FILE"
sed -i "s/_('History')/_('Histórico')/g" "$FILE"
sed -i "s/_('Trends')/_('Tendencias')/g" "$FILE"
sed -i "s/_('Override footer')/_('Sobrescribir pie')/g" "$FILE"
sed -i "s/_('No override')/_('Sin sobrescribir')/g" "$FILE"
sed -i "s/_('Include itemids in cell')/_('Incluir IDs de items en celda')/g" "$FILE"
sed -i "s/_('Update column')/_('Actualizar columna')/g" "$FILE"
sed -i "s/_('New column')/_('Nueva columna')/g" "$FILE"
sed -i "s/_('Update')/_('Actualizar')/g" "$FILE"
sed -i "s/_('Add')/_('Agregar')/g" "$FILE"
sed -i "s/_('Remove')/_('Eliminar')/g" "$FILE"
sed -i "s/_('User macros')/_('Macros de usuario')/g" "$FILE"

# TEXTOS DE AYUDA (makeHelpIcon)
sed -i "s/_('Only used when \\\\\'Layout\\\\\' is set to \\\\\'Column per pattern\\\\\'')/_('Solo se usa cuando el Diseño está configurado como Columna por patrón')/g" "$FILE"
sed -i "s/_('Checking this box means that the itemid will be broadcasted to listening widgets by clicking the cell in the column with the grouping value')/_('Marcar esta casilla significa que el ID del item se transmitirá a los widgets que escuchan al hacer clic en la celda de la columna con el valor de agrupación')/g" "$FILE"
sed -i "s/_('This is useful for when you have multiple columns and you want to broadcast multiple metrics to be plotted simultaneously')/_('Esto es útil cuando tienes múltiples columnas y quieres transmitir múltiples métricas para graficarlas simultáneamente')/g" "$FILE"
sed -i "s/_('If you know the item key pattern, you can specify it instead of the item name pattern by typing: \"key=<ITEM_KEY>\" for each pattern you want.')/_('Si conoces el patrón de clave de item, puedes especificarlo en lugar del patrón de nombre escribiendo: \"key=<CLAVE_ITEM>\" para cada patrón que desees.')/g" "$FILE"
sed -i "s/_('Wildcards are still supported for item key patterns.')/_('Los comodines aún son compatibles con los patrones de clave de item.')/g" "$FILE"
sed -i "s/_('The reason for item key pattern usage here is it is faster due to indexing.')/_('La razón para usar patrones de clave de item aquí es que es más rápido debido a la indexación.')/g" "$FILE"
sed -i "s/_('In order to find the key you need, to go the Latest data page, search for your item patterns and then check the \"Show details\" box. The key for each item will display below the item name in the \"Name\" column')/_('Para encontrar la clave que necesitas, ve a la página de Últimos datos, busca tus patrones de items y marca la casilla \"Mostrar detalles\". La clave de cada item se mostrará debajo del nombre del item en la columna \"Nombre\"')/g" "$FILE"
sed -i "s/_('Customize the display text of the URL')/_('Personaliza el texto de visualización de la URL')/g" "$FILE"
sed -i "s/_('Instead of displaying the raw URL you can set arbitrary text to display instead. The URL will be encoded into the text you enter in this text box.')/_('En lugar de mostrar la URL sin formato, puedes establecer un texto arbitrario para mostrar. La URL se codificará en el texto que ingreses en este cuadro.')/g" "$FILE"
sed -i "s/_('You can also mix macros with text. Supported macros:')/_('También puedes mezclar macros con texto. Macros soportados:')/g" "$FILE"
sed -i "s/_('Customize the entire URL')/_('Personaliza la URL completa')/g" "$FILE"
sed -i "s/_('Instead of displaying the metric value as a URL, you can leverage the hosts and items from the returned results to create a fully customized URL. You can also just simply enter any valid URL (i.e. https:\/\/www.zabbix.com)')/_('En lugar de mostrar el valor de la métrica como URL, puedes aprovechar los hosts e items de los resultados devueltos para crear una URL completamente personalizada. También puedes simplemente ingresar cualquier URL válida (ej. https:\/\/www.zabbix.com)')/g" "$FILE"
sed -i "s/_('Check this box to open the URL in a new browser tab, otherwise the link will open in the same tab')/_('Marca esta casilla para abrir la URL en una nueva pestaña del navegador, de lo contrario el enlace se abrirá en la misma pestaña')/g" "$FILE"
sed -i "s/_('Choose a function to aggregate all item patterns for this column for each host.')/_('Elige una función para agregar todos los patrones de items para esta columna por cada host.')/g" "$FILE"
sed -i "s/_('When using \\\\\'Column patterns aggregation\\\\\' include all itemids for broadcasting to other widgets')/_('Al usar Agregación de patrones de columna incluir todos los IDs de items para transmitir a otros widgets')/g" "$FILE"
sed -i "s/_('Set custom display text')/_('Establecer texto de visualización personalizado')/g" "$FILE"
sed -i "s/_('Create a fully custom URL')/_('Crear una URL completamente personalizada')/g" "$FILE"
sed -i "s/_('calculated')/_('calculado')/g" "$FILE"

echo ""
echo "✅ Traducción completada!"
echo "✅ Translation completed!"
echo ""
echo "📦 Los archivos originales están respaldados con extensión .backup"
echo "📦 Original files are backed up with .backup extension"
echo ""
echo "🔄 Ahora ejecuta:"
echo "🔄 Now run:"
echo "   sudo systemctl restart httpd"
echo ""
echo "📝 Si algo sale mal, puedes restaurar con:"
echo "📝 If something goes wrong, you can restore with:"
echo "   find $WIDGET_DIR -name '*.backup' -exec bash -c 'mv \"\$0\" \"\${0%.backup}\"' {} \;"
